import PageNotFound from "pages/PageNotFound";
import Submissions from "pages/ConferencePages/SubmissionsPage";
import Bidding from "pages/ConferencePages/BiddingPage";
import Reviews from "pages/ConferencePages/ReviewsPage";
import Mails from "pages/ConferencePages/EmailsPage";
import ComiteManagement from "pages/ConferencePages/ComiteManagement";
import ConferenceDefinitions from "pages/ConferencePages/ConferenceDefinitionsPage";
import ConferencePage from "pages/ConferencePages/ConferencePage";

const ConfRoutes = [
  {
    type: "title",
    name: "Conference",
    parentkey: "Details",
    display: true,
    permissions: ["All"],
  },
  {
    type: "collapse",
    name: "Description",
    submenu: "Details",
    route: "/MyConferences/Conference",
    component: <ConferencePage />,
    display: true,
    permissions: ["All"],
  },
  {
    type: "collapse",
    name: "Dates",
    submenu: "Details",
    route: "/MyConferences/Conference",
    component: <ConferencePage />,
    display: true,
    permissions: ["All"],
  },
  {
    type: "title",
    name: "Submissions",
    parentkey: "Submissions",
    display: true,
    permissions: ["All"],
  },
  {
    type: "collapse",
    name: "Create Submission",
    submenu: "Submissions",
    route: "/MyConferences/Conference/Submissions",
    component: <Submissions />,
    display: true,
    permissions: ["All"],
  },
  {
    type: "collapse",
    name: "My Submission",
    submenu: "Submissions",
    route: "/MyConferences/Conference/Submissions",
    component: <Submissions />,
    display: true,
    permissions: ["All"],
  },
  {
    type: "collapse",
    name: "All Submission",
    submenu: "Submissions",
    route: "/MyConferences/Conference/Submissions",
    component: <Submissions />,
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "title",
    name: "Bidding",
    parentkey: "Bidding",
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "collapse",
    name: "Bidding Process",
    submenu: "Bidding",
    route: "/MyConferences/Conference/Bidding",
    component: <Bidding />,
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "collapse",
    name: "Assignements",
    submenu: "Bidding",
    route: "/MyConferences/Conference/Bidding",
    component: <Bidding />,
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "title",
    name: "Reviews",
    parentkey: "Reviews",
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "collapse",
    name: "All Reviews",
    submenu: "Reviews",
    route: "/MyConferences/Conference/Reviews",
    component: <Reviews />,
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "collapse",
    name: "Assigned to me",
    submenu: "Reviews",
    route: "/MyConferences/Conference/Reviews",
    component: <Reviews />,
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "title",
    name: "Emails",
    parentkey: "Emails",
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "collapse",
    name: "Compose",
    submenu: "Emails",
    route: "/MyConferences/Conference/EMails",
    component: <Mails />,
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "collapse",
    name: "Send Invitation",
    submenu: "Emails",
    route: "/MyConferences/Conference/EMails",
    component: <Mails />,
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "title",
    name: "Administration",
    parentkey: "Settings",
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "collapse",
    name: "Comittee Management",
    submenu: "Settings",
    route: "/MyConferences/Conference/ComiteManagement",
    component: <ComiteManagement />,
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "collapse",
    name: "Conference Settings",
    submenu: "Settings",
    route: "/MyConferences/Conference/Settings",
    component: <ConferenceDefinitions />,
    display: true,
    permissions: ["Chair", "PC Member"],
  },
  {
    type: "404",
    name: "404",
    key: "404",
    route: "/PageNotFound",
    component: <PageNotFound />,
    display: false,
  },
];

export default ConfRoutes;